version: '3'

services:

    db_dev:
        image: mysql:8
        volumes:
          - ".volumes/mysql_dev:/var/lib/mysql"
        restart: always
        ports:
          - "3308:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=rick_and_morty
          - MYSQL_USER=dbuser
          - MYSQL_PASSWORD=dbpassword

